### ISSUE TITLE
Saving Pysparkling h2o mdeol on disk and then load into a single python application rather than pyspark

### ISSUE THREAD

**Issue by webcluster4u** [h2oai/sparkling-water#2852]
I have a PySpark code to train an H2o DRF model. I need to save this model to disk and then load it and use it a single python application not pyspark. Is that possible I save pysparkling models to disk and then load in a way I use in a single python application.

I know how to save h2o models to disk by using pyspark pipelines using this link (https://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/deployment/pysparkling_pipeline.html), but I need to use the model in a single python application, for example using  load model in h20

```
# load the model
saved_model = h2o.load_model(model_path)
```

```
from pysparkling.ml import H2ODRF
drf = H2ODRF(featuresCols = predictors,
                labelCol = response,
                columnsToCategorical = [response])
I can not find any document on this so I am asking this question here.
```

I appreciate if someone could help me find out above.

**Comment by mn-mikke** [comment]
Sparkling Water is an extension to Spark and requires spark runtime model training as well as for model scoring. In your single python application, you can still crate a local SparkSession a do with the model whatever you want.
```
from pyspark.sql import SparkSession
spark = (SparkSession.builder
  .master("local[*]")
  .appName("your_app_name")
  .getOrCreate())
```

If you train a single model with SW api. you can still load it with h2o api:
```
drfModel.save("/tmp/myModel")
saved_model = h2o.import_mojo("/tmp/myModel/mojo_model")
```
and use it as in the example [here](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/save-and-load-model.html#saving-and-importing-mojos). But in this case you will need a local h2o runtime instead of a local  Spark runtime running.

**Comment by webcluster4u** [comment]
Hi,

I ma trying to save my SW model to disk
```

drf = H2ODRF(featuresCols = predictors,
                labelCol = response,
                columnsToCategorical = [response])
print("Started fitting the h2o model")
model = drf.fit(train_f)
output=model.transform(test_f)

pth='file:///dbfs/my_data/h2o_model'
drf.write().overwrite().save(pth)
```

but it seems that there is no mojo_model path and it doesnt save as mojo

```
ls -l /dbfs/my_data/h2o_model
total 4
drwxrwxrwx 2 root root 4096 Jan 21 01:50 metadata/
```

**Comment by webcluster4u** [comment]
oh, my bad, I should have saved the model.
