### ISSUE TITLE
How to use pysparkling with LDAP?

### ISSUE THREAD

**Issue by Dom-nik** [h2oai/sparkling-water#62]
Hello,

I'm running pysparkling (Sparkling Water 1.5.16) with a command like this:
`$SPARKLING_HOME/bin/pysparkling --num-executors 3 --executor-memory 20g --executor-cores 10 --driver-memory 20g --master yarn-client --conf "spark.scheduler.minRegisteredResourcesRatio=1" --conf "spark.ext.h2o.topology.change.listener.enabled=false" --conf "spark.ext.h2o.node.network.mask=155.111.184.0/24" --conf "spark.ext.h2o.fail.on.unsupported.spark.param=false" --conf "spark.ext.h2o.ldap.login=true" --conf "spark.ext.h2o.login.conf=/opt/sparkling-water/ldap.conf" --conf "spark.ext.h2o.user.name=<USER>"`

and when I try to start H2OContext:

```
from pysparkling import *
hc= H2OContext(sc).start()
```

I get a bunch of access error:

> javax.security.auth.login.LoginException: User not found.
> ...
> javax.security.auth.login.LoginException: Error obtaining user info.
> ...
> ValueError: Cannot connect to H2O server. Please check that H2O is running at http://155.111.190.82:54321/3/

I kinit before starting the tool. Can you point me to the documentation that says how to pass a username to the `start()` command or otherwise solve this problem?

**Comment by stefan8888** [comment]
Hi Dom-nik,

I don't think it's possible yet to pass an username as an argument. I'm running pysparkling (Sparkling Water 1.6) and as a workaround I slightly adjusted the `getOrCreate` method within `context.py`.  After that you can either rebuild the pysparkling package or import the adjusted `context.py` file as an additional module. Hence:

- Wihtin `context.py` replace `h2o.init(ip=h2o_context._client_ip, port=h2o_context._client_port, start_h2o=False, strict_version_check=False)` by
`h2o.init(ip=h2o_context._client_ip, port=h2o_context._client_port, start_h2o=False, strict_version_check=False, username=<USER>, password=<PASSWORD>)`

It might not be the nicest workaround but it does the job. 

Btw I'm using the Hash file authentication and I'm not sure whether it'll also work for LDAP.

**Comment by jakubhava** [comment]
Hi @Dom-nik and @stefan8888 ,
 with this commit https://github.com/h2oai/sparkling-water/commit/566d2a709112f6a1d966c824c41d9fe536dca0dc it's possible to pass arbitrary client configuration to python `h2o.connect` method. We don't do this as part of the `H2OConf` object since we want to keep the configuration object consistent between scala and python and this change is specific to python.

Right now you can use the same command as before to start sparkling-water( same env variables ) and in pysparkling do:

```
from pysparkling import *
hc= H2OContext.getOrCreate(sc, auth=XX)
```
where `XX` is either a (username, password) pair for basic authentication, or one of the requests.auth authenticator objects.

Just to confirm - this should work with ldap, kerberos and hash authentifications.

Closing this issue for now, please feel free reopen when you still have same problems with this
