### ISSUE TITLE
Add Pipeline support for GLM algorithm

### ISSUE THREAD

**Issue by ngallot** [h2oai/sparkling-water#657]
Hi,
Currently, only GBM algorithms can implement Spark pipelines. I'm working on a use case where it would be nice to have pipeline support for GLM as well. I guess this could be done by creating an H2OGLM, similar to H2OGBM. What do you guys think?

**Comment by jakubhava** [comment]
Ho @ngallot , exactly. At this stage it's just technical task. If you would like to contribute, it would be great :) Otherwise I can't guarantee any estimate when this can be done

**Comment by ngallot** [comment]
Thanks for your answer @jakubhava, ok I'll start working on this soon!

**Comment by jakubhava** [comment]
Amazing, this would be great help! I would start with implementing the Scala part. You can inspire yourself at H2OGBM as you already mention :)

**Comment by jakubhava** [comment]
Hi @ngallot, I was discussing the future development of exposed algos such as GLM, GBM in Sparkling Water. We think that we could actually generate automatically most of the code for these algos for Sparkling Water.

I think it would be better write code generator for these algos instead of writing GLM by hand. What do you think, would this be something you would like to work on?

**Comment by jakubhava** [comment]
Closing this issue, this is on our roadmap
